function [BW,maskedImage] = segmentImage(RGB)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(RGB) segments image RGB using
%  auto-generated code from the imageSegmenter app. The final segmentation
%  is returned in BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 13-Aug-2019
%----------------------------------------------------


% Convert RGB image into L*a*b* color space.
X = rgb2lab(RGB);

% Create empty mask.
BW = false(size(X,1),size(X,2));

% Flood fill
row = 2189;
column = 3335;
tolerance = 5.000000e-02;
normX = sum((X - X(row,column,:)).^2,3);
normX = mat2gray(normX);
addedRegion = grayconnected(normX, row, column, tolerance);
BW = BW | addedRegion;

% Draw Rectangle
xPos = [3180.3662 3349.3208 3349.3208 3180.3662];
yPos = [2042.5627 2042.5627 2117.1843 2117.1843];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Draw Freehand
xPos = [3335.2413 3329.6095 3304.2663 3300.0424 3297.2265 3294.4106 3291.5947 3288.7788 3287.3708 3285.9629 3284.5549 3281.7390 3280.3310 3280.3310 3291.5947 3291.5947 3293.0026 3293.0026 3293.0026 3294.4106 3294.4106 3295.8185 3297.2265 3298.6345 3298.6345 3298.6345 3298.6345 3300.0424 3302.8583 3312.7140 3322.5697 3328.2015 3333.8333 3335.2413 3339.4652 3346.5049 3349.3208 3352.1367 3353.5447 3353.5447 3353.5447 3353.5447 3347.9129 3342.2811 3338.0572 3335.2413 3333.8333 3331.0174 3329.6095 3326.7936 3325.3856];
yPos = [2159.4229 2160.8309 2173.5025 2176.3184 2176.3184 2177.7263 2179.1343 2180.5422 2181.9502 2183.3581 2184.7661 2186.1741 2187.5820 2188.9900 2200.2536 2201.6616 2201.6616 2204.4775 2205.8854 2210.1093 2211.5172 2215.7411 2217.1491 2219.9650 2225.5968 2227.0048 2228.4127 2228.4127 2228.4127 2225.5968 2219.9650 2217.1491 2214.3332 2211.5172 2208.7013 2207.2934 2207.2934 2207.2934 2207.2934 2205.8854 2203.0695 2193.2138 2186.1741 2179.1343 2173.5025 2172.0945 2172.0945 2169.2786 2167.8706 2166.4627 2162.2388];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Draw Freehand
xPos = [3281.7390];
yPos = [2183.3581];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Draw Polygon
xPos = [3280.3310 3326.7936 3350.7288 3308.4901];
yPos = [2181.9502 2153.7911 2201.6616 2225.5968];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Create masked image.
maskedImage = RGB;
maskedImage(repmat(~BW,[1 1 3])) = 0;
end

